kind: DeploymentConfig
apiVersion: v1
metadata:
  name: novel-admin
  namespace: novel
  labels:
    app: novel-admin
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: novel-admin
    deploymentconfig: novel-admin
  template:
    metadata:
      labels:
        app: novel-admin
        deploymentconfig: novel-admin
    spec:
      volumes:
        - name: tmp-volume-1
          emptyDir: {}
        - name: applog
          emptyDir: {}
        - name: filebeat-data
          emptyDir: {}
        - name: heapdump-volume
          hostPath:
            path: /app/heapdump
      containers:
        - name: novel-admin
          image: >-
            docker-test-local.art.ocp.csvw.com/svw-idp-test/idp-selfcare-pro:1.0.87
          ports:
            - name: jolokia
              containerPort: 8778
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          env:
            - name: JAVA_OPTIONS
              value: >-
                -Xms1024m -Xmx1024m -Djava.security.egd=file:/dev/./urandom
                -Dfile.encoding=UTF-8 -Duser.language=zh -Duser.country=CN
                -XX:+HeapDumpOnOutOfMemoryError
                -XX:HeapDumpPath=/deployments/heapdump/idp-selfcare-pro.hprof
                -Drocketmq.client.logRoot=/var/log/app/rocketmq
                -Drocketmq.client.logFileMaxIndex=10
                -Drocketmq.client.logFileMaxSize=20971520
            - name: GC_MAX_METASPACE_SIZE
              value: '200'
            - name: CONFIGSERVER_URL
              value: 'http://idp-configserv-pro:8080'
            - name: MAXFILESIZE
              value: 50MB
            - name: TOTALSIZECAPS
              value: 7GB
            - name: SERVICENAME
              value: idp-selfcare-pro
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - name: tmp-volume-1
              mountPath: /tmp
            - name: heapdump-volume
              mountPath: /deployments/heapdump
            - name: applog
              mountPath: /var/log/app
          readinessProbe:
            httpGet:
              path: /esc-selfcare/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 60
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
        - name: filebeat
          image: 'dt-cluster.ocp.csvw.com:5000/library/filebeat:6.5.4'
          env:
            - name: APP_NAME
              value: idp-selfcare-pro
            - name: APP_LOG_TOPIC
              value: test-svw-idp
            - name: APP_CACHE_LOG_TOPIC
              value: test-cache-svw-idp
            - name: KAFKA_HOSTS
              value: >-
                ["test-ece1.kafka.sitc:9092","test-ece2.kafka.sitc:9092","test-ece3.kafka.sitc:9092"]
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - name: tmp-volume-1
              mountPath: /tmp
            - name: applog
              mountPath: /var/log/app
            - name: filebeat-data
              mountPath: /usr/share/filebeat/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        type: primary
      securityContext: {}
      schedulerName: default-scheduler
status:
  latestVersion: 432
  observedGeneration: 658
  replicas: 1
  updatedReplicas: 0
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: config change
    causes:
      - type: ConfigChange
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-04-25T08:51:51Z'
      lastTransitionTime: '2022-04-25T08:51:51Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2022-04-27T02:33:37Z'
      lastTransitionTime: '2022-04-27T02:33:37Z'
      reason: ProgressDeadlineExceeded
      message: replication controller "idp-selfcare-pro-431" has failed progressing
  readyReplicas: 1
